### ISSUE TITLE
BUSCO v3 ValueError: 'Contig' is not in list

### ISSUE THREAD

**Issue by guifftc** [blobtoolkit/blobtools2#10]
Dear developers,

I cannot feed blobtools2 add --busco with my busco v3 euk db9 full _table.tsv in Mac OS X:

Traceback (most recent call last):
  File "/Users/guifre500/bioinfo/blobtoolkit/blobtools2/lib/add.py", line 153, in <module>
    main()
  File "/Users/guifre500/bioinfo/blobtoolkit/blobtools2/lib/add.py", line 120, in main
    meta=meta)
  File "/Users/guifre500/bioinfo/blobtoolkit/blobtools2/lib/busco.py", line 60, in parse
    parsed.append(parse_busco(file, identifiers=kwargs['dependencies']['identifiers']))
  File "/Users/guifre500/bioinfo/blobtoolkit/blobtools2/lib/busco.py", line 27, in parse_busco
    contig_index = columns.index('Contig')
ValueError: 'Contig' is not in list

I'm no expert, but I've checked busco.py and the problem is that my BUSCO output, at line 5, has "Sequence" as column name instead of Contig, which is what the script wants to parse. So seems easy to fix.

Thanks!

**Comment by rjchallis** [comment]
Thanks for letting me know about this. I'm hoping to get round to some BlobToolKit updates next week so I'll be sure to fix this one then.
