### ISSUE TITLE
add soft masked assembly

### ISSUE THREAD

**Issue by Jadziaa** [blobtoolkit/blobtools2#7]
Hello, 

I wanted to add soft masked assembly (PacBio reads) to the BlobDir using this command: ../BLOBTOOLS/blobtools2/blobtools create --fasta carp_pbjelly.fa NETHERLANDS 

But I got and error:

Loading sequences from carp_pbjelly.fa
 - processing Contig76388: : 76354it [01:00, 7943.08it/s]Traceback (most recent call last):
  File "/Data/jadzia/ANUSH/BLOBTOOLS/blobtools2/lib/add.py", line 152, in <module>
    main()
  File "/Data/jadzia/ANUSH/BLOBTOOLS/blobtools2/lib/add.py", line 119, in main
    meta=meta)
  File "/Data/jadzia/ANUSH/BLOBTOOLS/blobtools2/lib/fasta.py", line 56, in parse
    _gc_portions[seq_id], _n_counts[seq_id] = base_composition(seq_str)
  File "/Data/jadzia/ANUSH/BLOBTOOLS/blobtools2/lib/fasta.py", line 29, in base_composition
    gc_portion = float("%.4f" % (gc_count / acgt_count))
ZeroDivisionError: division by zero
 - processing Contig76388: : 76354it [01:00, 1271.37it/s]

I am attaching few lines of the assembly test.txt

**Comment by rjchallis** [comment]
Hi

Most likely cause would be if Contig76388 contains no ACGT (or acgt as it is soft masked) bases. The file didn't attach but if there is sequence in Contig76388 could you attach that then I can try to dig a bit deeper.

**Comment by Jadziaa** [comment]
That's right, Contig76388 contained only NNNNNNNNNNN.

Thanks a lot :)
